org: hossamyahia1017
app: upload-image-to-aws-s3-app
service: upload-image-to-aws-s3 #Name of your App

provider:
 name: aws
 runtime: nodejs10.x # Node JS version
 memorySize: 1024
 timeout: 30
 stage: production
 region: eu-central-1 # AWS region

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY /{proxy+}
     - http: ANY /